name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
        default: "1.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0
          8.0
          2.1

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore src/MemoryPack/MemoryPack.csproj

    # Build the project
    - name: Build projects
      run: dotnet build src/MemoryPack/MemoryPack.csproj --configuration Release --no-restore

    # Run tests (опционально)
    - name: Run tests
      run: dotnet test src/MemoryPack/MemoryPack.csproj --configuration Release --no-build

    # Set the version
    - name: Set version
      run: |
        echo "Setting version to ${{ github.event.inputs.version }}"
        dotnet pack src/MemoryPack/MemoryPack.csproj --configuration Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/MemoryPack.Core/MemoryPack.Core.csproj --configuration Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/MemoryPack.Generator/MemoryPack.Generator.csproj --configuration Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs

    # Publish packages
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
      run: |
        for pkg in ./nupkgs/*.nupkg; do
          dotnet nuget push "$pkg" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json"
        done
